### ISSUE TITLE
Page title twice

### ISSUE THREAD

**Issue by millo2k** [digisavvy/some-like-it-neat#71]
It seems the page title is appearing twice on all pages (in the browser tabs).... I've not done anything to it. Any ideas?

**Comment by millo2k** [comment]
So it reads:
Site Name | Page TitlePageTitle

I have looked through a load of files but cant see where this is being produced from???

**Comment by millo2k** [comment]
I have no SEO plugins and have disabled the three plugins I am using and theres no change.

Any ideas?

Thanks

**Comment by digisavvy** [comment]
Hey there,
This issue has been resolved. There was some legacy filter adding an extra title there, it's been removed and pushed.

**Comment by millo2k** [comment]
Brilliant, I'm still having problems with the newer template so dont want to pull the new files. Could you let me know where to change it? Thanks
